### ISSUE TITLE
Failing to install according to documentation

### ISSUE THREAD

**Issue by vingeldal** [boost-cmake/bcm#22]
I'm failing to install BCM. I'm assuming that it is an issue at my side but I'v followed the documentation exactly and I was thinking that maybe there are some prerequisites I missed; which could be part of the documentation to help with resolving issues like mine.

* I'v cloned the repo next to my other repos.
* Then, in the bcm repo, I did:
    mkdir build
    cd build
    cmake ..
    cmake --build . --target install
* Then, in the CMakeLists.txt of my own project, tried to use;
    find_package(BCM)
    include(BCMDeploy)
    bcm_deploy(TARGETS config INCLUDE include)

For me find_package(BCM) failes with:

-- Could NOT find BCM (missing: BCM_DIR)
CMake Error at pi_core/pi_tracing/CMakeLists.txt:4 (include):
  include could not find load file:

    BCMDeploy

CMake Error at pi_core/pi_tracing/CMakeLists.txt:5 (include):
  include could not find load file:

    BCMSetupVersion

CMake Error at pi_core/pi_tracing/CMakeLists.txt:7 (bcm_setup_version):
  Unknown CMake command "bcm_setup_version".

-- Configuring incomplete, errors occurred!

**Comment by pfultz2** [comment]
Doing `cmake --build . --target install` should install BCM into `/usr/local`. Where did it install `BCM` when you called `cmake --build . --target install`?

**Comment by vingeldal** [comment]
It actually installs to /usr/local/share/bcm/cmake/
The installation reports a success and I can see BCMConfig.cmake in there.
It seems like CMake just can't find it anyway.
I desperately tried to append all kinds of paths to both CMAKE_PREFIX_PATH and CMAKE_MODULE_PATH but I still get the exact same problem. The paths I'm trying are:

list(APPEND CMAKE_PREFIX_PATH "/usr/local/share/bcm/cmake")
list(APPEND CMAKE_PREFIX_PATH "/usr/local/share/bcm")
list(APPEND CMAKE_PREFIX_PATH "/usr/local/share")
list(APPEND CMAKE_PREFIX_PATH "/usr/local")
list(APPEND CMAKE_MODULE_PATH "/usr/local/share/bcm/cmake")
list(APPEND CMAKE_MODULE_PATH "/usr/local/share/bcm")
list(APPEND CMAKE_MODULE_PATH "/usr/local/share")
list(APPEND CMAKE_MODULE_PATH "/usr/local")
set(BCM_DIR "/usr/local/share/bcm/cmake")

**Comment by pfultz2** [comment]
`find_package` needs to be called after `project()` command, otherwise the search paths are not setup. Are you calling `project` before `find_package`?

**Comment by pfultz2** [comment]
Do you have an example to point to? When I create a project like this:

```cmake
cmake_minimum_required(VERSION 3.5)
find_package(BCM)
include(BCMDeploy)
add_library(config INTERFACE)
bcm_deploy(TARGETS config INCLUDE include)
```

It works for me.

**Comment by vingeldal** [comment]
I do it just like you but I don't get it to work. But now I at least feel confident that I'm using it right there is probably just something wrong with the project since before I tried using BCM.
Unfortunately I can't show an example of what I'm doing because I'm trying to use this at work. It's 
a rather big project and a little bit messy and I'm still learning how it's supposed to work.
There's probably some corner of the project where someone has done some dark magic which messes with my patch.
I'll just have to keep digging around in our own things.
Thanks for the help.
