### ISSUE TITLE
auto-linking in bcm_package is bad

### ISSUE THREAD

**Issue by ldionne** [boost-cmake/bcm#3]
You save the need to specify one thing to link against, but you introduce an implicit target dependency. I think this feature should be removed.

**Comment by pfultz2** [comment]
Are you talking about auto-link for the tests?

**Comment by ldionne** [comment]
Yes.

**Comment by pfultz2** [comment]
> You save the need to specify one thing to link against

Its more than one thing. This needs to be linked for every test. So rather than linking multiple times:

```cmake
bcm_test(NAME test1 SOURCES test1.cpp)
target_link_libraries(test1 foo)

bcm_test(NAME test12 SOURCES test12.cpp)
target_link_libraries(test12 foo)

bcm_test(NAME test3 SOURCES test3.cpp)
target_link_libraries(test3 foo)

# Don't link against the package
bcm_test(NAME test3 SOURCES test3.cpp)
```

One can can just specify explicitly not to link against the package:

```cmake
bcm_test(NAME test1 SOURCES test1.cpp)

bcm_test(NAME test2 SOURCES test2.cpp)

bcm_test(NAME test3 SOURCES test3.cpp)

# Don't link against the package
bcm_test(NAME test3 SOURCES test3.cpp NO_TEST_LIBS)
```

Linking a test against the package is quite common so it makes this use case much easier. Whereas not linking against the package is quite uncommon.

**Comment by ldionne** [comment]
> This needs to be linked for every test.

Yeah, and that's only tedious because you list all of your unit tests manually instead of using `file(GLOB ...)` and using a `foreach`. I know `file(GLOB ...)` is discouraged, but that is a silly guideline (the rationale behind is not compelling, and it's unjustifiable when you have 1000+ unit tests, e.g. Hana).

**Comment by ldionne** [comment]
I __really__ think the current setup is promoting the wrong set of guidelines, and I wouldn't use it myself because of this. Just my .02.

**Comment by pfultz2** [comment]
I agree with you about the globbing, however:

1) Some authors will want to follow cmake's guidelines about globbing
2) Some tests in some libraries are not organized as neatly to be able to do file globbing.

> I really think the current setup is promoting the wrong set of guidelines

How so? The globbing solutions seems to promote the wrong set of guidelines.

> I wouldn't use it myself because of this. Just my .02.

The whole setup? As you can disable this in `bcm_test` with `NO_TEST_LIBS` or you can add the tests manually and just use `bcm_mark_as_test`.

**Comment by ldionne** [comment]
> Some authors will want to follow cmake's guidelines about globbing

As authors of this package, we (well, you) should set the best practices that you expect to see followed in the Boost (and non-Boost) packages that are going to use it. If we agree this best practice is to adding tests in a batch and link all libraries explicitly, then that's what we should do.

> Some tests in some libraries are not organized as neatly to be able to do file globbing

Boost libraries are expected to be. For the rest, they can create a tiny wrapper around `bcm_test` to populate their libraries to link against.

> The whole setup?

Perhaps not the whole setup, but I do think it is a big concern, yeah. The way tests are added is one of the most important parts of BCM, since it is used all the time and it is what changes the most often. I think the worst part is that it encourages the wrong best practice, which is why I'm so grumpy about it.

**Comment by pfultz2** [comment]
> Boost libraries are expected to be.

They are? Boost.Config is not like that. The `.ipp` files can be added using globbing but the rest of the tests cannot. Other libraries are very similar in boost as well.

> I do think it is a big concern, yeah.

What concerns you about this?

> The way tests are added is one of the most important parts of BCM, since it is used all the time

Yes, and I have set this up to how tests are created most of the time, but I still provide the flexibility to disable the linking or even provide a way to add tests created manually as well

> I think the worst part is that it encourages the wrong best practice

What wrong best practice?

**Comment by ldionne** [comment]
> What wrong best practice?

To use a global and implicit setting for controlling libraries linked to unit tests.

**Comment by pfultz2** [comment]
> To use a global and implicit setting for controlling libraries linked to unit tests.

But thats what most libraries do, including hana.

**Comment by ldionne** [comment]
Closing as sort-of duplicate of #2.
